#Deutsch/ Trage in der lücke von " " denn gewünschten Command ein um diesen Command deaktivieren zu können
#English/ Enter the desired command in the space of "" in order to be able to deactivate this command 

#Command hier rein schreiben
cmd:
  - "kill"
  - "status"


#Deutsch /fals fragen auftauchen schreibt denn Author von diesen Plugin an!

#Viel Spaß 


#English/ if ask come up because the author of this plugin writes to! 

#Have fun 

